### PR TITLE
CAR Pool & More

### PR DESCRIPTION
**Pull request by expede**

### CODE REVIEW

**Comment by expede** [comment]
FYI @justincjohnson (it's optional)

**Comment by justindotpub** [comment]
FYI, I mentioned this PR to @b5 in ipfs thing discord and it sounds like he's going to add to the data transfer track.  He already had a WIP item for CAR Pool.

**Comment by bmann** [comment]
@justincjohnson it wasn’t supposed to yet. Brooke PR’d into here quickly before going on vacation. 

Can you and @matheus23 please take the individual issues / PRs and get them submitted upstream on behalf of Brooke. And get your own submitted as well.

**Comment by justindotpub** [comment]
Since I couldn't change the base of this PR to upstream, I replaced it with https://github.com/ipfs-shipyard/ipfs-thing-2022/pull/52.

**Comment by expede** [comment]
Thanks @justincjohnson! Closing in favour of [ipfs-shipyard#71](https://github.com/ipfs-shipyard/ipfs-thing-2022/pull/79)

**Pull request closed without merging**
